version: "3.2"

services:
  app:
    build: ./init_app
    command: bash -c "python database_setup.py && scrapy crawl ca_walmart"
    ports:
      - 8000
    volumes:
      - ".:/cornershop"
      - type: tmpfs
        target: /cornershop/tmp/pids/
    env_file:
      - ".env"
    tty: true
    stdin_open: true
    # environment: